<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Resources\" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Hybrid2D" Version="*" />
    </ItemGroup>

</Project>
